name: agent-lightning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  # libgcc and libstdcxx require: export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH
  - libgcc-ng
  - libstdcxx-ng
  - pip
  - pip:
    - agentlightning[verl]>=0.3.0
    - verl==0.5.0
    - openai==1.99.5
    - torch==2.8.0  --index-url https://download.pytorch.org/whl/cu128
    - torchvision==0.23.0 --index-url https://download.pytorch.org/whl/cu128
    - vllm==0.10.2
    # flash-attn installation requires torch. pip install it manually
    # - flash-attn
    - gdown
    - langgraph<1.0
    - langchain[openai]<1.0
    - langchain-community
    - langchain-text-splitters<1.0
    - sqlparse
    - nltk
    - agentops==0.4.21

# Download training data in agent-lightning/examples/spider/data
# gdown --fuzzy https://drive.google.com/file/d/1oi9J1jZP9TyM35L85CL3qeGWl2jqlnL6/view
# unzip -q spider-data.zip -d data
# rm spider-data.zip
